const state = {
    scrollAnimationFrame: null,
    lastScrollFrameTime: 0,
    isJPressed: false,
    isKPressed: false,
    scrollBoundaryFrames: 0,
    highlightedField: null,
    mode: "normal",
    pendingPrefixKey: null,
    lastFindQuery: "",
    activeFindQuery: "",
    activeFindMatchIndex: -1,
    findMatches: [],
    didTruncateFindMatches: false,
    findUsesCustomHighlights: false,
    findAllMatchesHighlight: null,
    keyHintMode: "hidden",
    pendingFindUiSearchFrame: null,
    pendingFindUiSearchRequest: null
};
