const state = {
    scrollAnimationFrame: null,
    lastScrollFrameTime: 0,
    isJPressed: false,
    isKPressed: false,
    scrollBoundaryFrames: 0,
    highlightedField: null,
    mode: "normal",
    pendingPrefixKey: null,
    lastFindQuery: "",
    activeFindQuery: "",
    activeFindMatchIndex: -1,
    findMatches: [],
    didTruncateFindMatches: false,
    findUsesCustomHighlights: false,
    findMatchHighlight: null,
    findActiveHighlight: null,
    keyHintMode: "hidden",
    pendingFindUiSearchFrame: null,
    pendingFindUiSearchRequest: null,
    pendingFindUiDebounceTimer: null
};
